# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1253211977);
user_pref("app.update.lastUpdateTime.background-update-timer", 1253211976);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1253211976);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1253211977);
user_pref("app.update.lastUpdateTime.places-maintenance-timer", 1253212017);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1253211978);
user_pref("app.update.mode", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.download.dir", "C:\\temp");
user_pref("browser.download.folderList", 2);
user_pref("browser.download.manager.showWhenStarting", false);
user_pref("browser.history_expire_days.mirror", 180);
user_pref("browser.migration.version", 1);
user_pref("browser.places.smartBookmarksVersion", 1);
user_pref("browser.preferences.advanced.selectedTabIndex", 2);
user_pref("browser.privatebrowsing.autostart", true);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.update", false);
user_pref("browser.sessionstore.resume_session_once", true);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage", "about:blank");
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.1.3");
user_pref("browser.startup.page", 0);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.tabs.warnOnOpen", false);
user_pref("dom.disable_open_during_load", false);
user_pref("extensions.enabledItems", "{CAFEEFAC-0016-0000-0011-ABCDEFFEDCBA}:6.0.11,{CAFEEFAC-0016-0000-0015-ABCDEFFEDCBA}:6.0.15,jqs@sun.com:1.0,{20a82645-c095-46ed-80e3-08825760534b}:1.1,{a6fd85ed-e919-4a43-a5af-8da18bda539f}:1.0.2,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.5.3");
user_pref("extensions.lastAppVersion", "3.5.3");
user_pref("extensions.newAddons", false);
user_pref("extensions.update.notifyUser", false);
user_pref("general.autoScroll", false);
user_pref("general.useragent.extra.microsoftdotnet", "(.NET CLR 3.5.30729)");
user_pref("intl.charsetmenu.browser.cache", "windows-1252, UTF-8");
user_pref("layout.spellcheckDefault", 0);
user_pref("microsoft.CLR.auto_install", false);
user_pref("network.cookie.prefsMigrated", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("security.warn_entering_weak", false);
user_pref("security.warn_viewing_mixed", false);
user_pref("signon.rememberSignons", false);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1255805041);
