<?xml version="1.0" encoding="utf-8"?>
<Database Name="ETCM" Class="ETCMDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=alliance5;Initial Catalog=ETCM;Integrated Security=True" SettingsObjectName="Envision.ConfigurationManagement.Properties.Settings" SettingsPropertyName="ETCMConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Issue" Member="Issues">
    <Type Name="Issue">
      <Column Name="PRN" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RequestType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="AssignedTo" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="ReportedBy" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Priority" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Severity" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DateReported" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateFixed" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateClosed" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AssignedToProject" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ReportedInVersion" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CodeReviewed" Type="System.String" DbType="NChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="Product" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Component" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>